name: Spring Boot Build & Gradle CI/CD

on: 
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            whoami
            ls -al
            cd api/src/main/resources
            touch ./application.properties
            echo "${{ secrets.PROPERTIES }}" > ./application.properties
            cd ../../../build/resources/main
            echo "${{ secrets.PROPERTIES }}" > ./application.properties
            
  build-and-run:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: |
          pwd
          ls -al
          chmod 777 ./gradlew
          ./gradlew clean build
          cd ./build/libs
          chmod 777 ./replnote-0.0.1-SNAPSHOT.jar
          nohup java -jar ./replnote-0.0.1-SNAPSHOT.jar &
