name: Spring Boot Build & Gradle CI/CD

on: 
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            pwd
            git pull origin main
  build-and-run:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          pwd
          chmod 777 ./gradlew
          ./gradlew clean build
          cd ./build/libs
          chmod 777 ./replnote-0.0.1-SNAPSHOT.jar
          nohup java -jar ./replnote-0.0.1-SNAPSHOT.jar &
