name: Spring Boot Build & Gradle CI/CD

on: 
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        run: |
          cd ./api
          ./gradlew clean build
          cd ./build/libs
          nohup java -jar replnote-0.0.1-SNAPSHOT.jar &
